<a href="https://colab.research.google.com/github/Pranav-J-Kumar/data-science/blob/main/EXP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing library
import numpy as np
  
# Creating two 2-D matrix
matrix1 = np.array([[1, 3], [2, 6]])
matrix2 = np.array([[0, 1], [1, 9]])
print("Original 2-D matrix:")
print(matrix1)
print(matrix2)
  
# Output
print("Outer Product of the two matrix is:")
result = np.outer(matrix1, matrix2)
print(result)

Original 2-D matrix:
[[1 3]
 [2 6]]
[[0 1]
 [1 9]]
Outer Product of the two matrix is:
[[ 0  1  1  9]
 [ 0  3  3 27]
 [ 0  2  2 18]
 [ 0  6  6 54]]


In [2]:
import numpy as np
  
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [3]:
import numpy as np 
       
# 2D array  
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4,]]  
   
print("\nSum of arr : ", np.sum(arr)) 
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0)) 
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1))
  
print("\nSum of arr (keepdimension is True): \n",
      np.sum(arr, axis = 1, keepdims = True))


Sum of arr :  279
Sum of arr(axis = 0) :  [52 25 93 42 67]
Sum of arr(axis = 1) :  [120  75  84]

Sum of arr (keepdimension is True): 
 [[120]
 [ 75]
 [ 84]]


In [4]:
import numpy as geek
  
in_arr1 = geek.array([[2, -7, 5], [-6, 2, 0]])
in_arr2 = geek.array([[0, -7, 8], [5, -2, 9]])
   
print ("1st Input array : ", in_arr1)
print ("2nd Input array : ", in_arr2)
   
    
out_arr = geek.multiply(in_arr1, in_arr2) 
print ("Resultant output array: ", out_arr) 

1st Input array :  [[ 2 -7  5]
 [-6  2  0]]
2nd Input array :  [[ 0 -7  8]
 [ 5 -2  9]]
Resultant output array:  [[  0  49  40]
 [-30  -4   0]]
