<a href="https://colab.research.google.com/github/Pranav-J-Kumar/data-science/blob/main/EXP_2_c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
print("Array is:")
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print("U")
print(U)
print("S")
print(s)
print("VT")
print(VT)

Array is:
[[1 2]
 [3 4]
 [5 6]]
U
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S
[9.52551809 0.51430058]
VT
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
